default:
  module: src.server.tasks.alfworld.ALFWorld
  parameters:
    name: alfworld-std
    concurrency: 16
    data_path: "/app/data/alfworld"
    config_path: "/app/src/server/tasks/alfworld/configs/base_config.yaml"
    prompts_path: "/app/src/server/tasks/alfworld/prompts/alfworld_multiturn_plan_first.json"
    split: "new_std"
    max_step: 20
    tools:
      - type: "function"
        function:
          name: "take_action"
          description: "Take an action."
          parameters:
            type: "object"
            properties:
              action:
                type: "string"
                description: "The action you would like to take"
            required:
              - "action"
            additionalProperties: False

alfworld-std:
  parameters:
    name: alfworld-std
    split: "new_std"

alfworld-env_train:
  parameters:
    name: alfworld-env_train
    split: "train_valid"
